<?php
/**
 *
 *  * @package   yii2-easy-ajax
 *  * @author    Gianpaolo Scrigna <letsjump@gmail.com>
 *  * @link https://github.com/letsjump/yii2-easy-ajax
 *  * @copyright Copyright &copy; Gianpaolo Scrigna, beintech.it, 2017-2020
 *  * @version   1.0.0
 *
 */

namespace letsjump\AnchorJS;

use Yii;
use yii\base\Widget;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\View;

class AnchorJS extends Widget
{
    public $add = '';
    public $options = [];
    
    protected $_defaultOptions = [
        'placement' => 'right',
        'visible'   => 'hover',
        'icon'      => '',
        'class'     => '',
        'base'      => '',
        'truncate'  => 64,
        'ariaLabel' => 'Anchor',
        'titleText' => ''
    ];
    
    public function init()
    {
        AnchorJSAsset::register($this->getView());
        
        parent::init(); // TODO: Change the autogenerated stub
    }
    
    /**
     * @return array
     */
    public function getOptions()
    {
        if (isset(Yii::$app->params['anchor-js'])) {
            return ArrayHelper::merge($this->_defaultOptions, Yii::$app->params['anchorjs'], $this->options);
        }
        
        return ArrayHelper::merge($this->_defaultOptions, $this->options);
    }
    
    public function run()
    {
        $options = Json::encode($this->getOptions());
        $this->getView()->registerJs(<<<JS
            var anchors = new AnchorJS();
            anchors.add('{$this->add}');
            anchors.options = {$options};
JS
            , View::POS_LOAD
        );
        
        parent::run(); // TODO: Change the autogenerated stub
    }
}